name: Testing and distribution
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-something:
    name: Test something
    runs-on: ubuntu-latest
    steps:

      - name: Upload folder to biglocalnews.org
        uses: biglocalnews/upload-files@v3
